#!/bin/sh
# BigFred loco-server (dcc-bus is spawned via supervisord as: bigfred dcc-bus …)
# /usr/bin/bigfred resolves /data/opt then /opt.

BIN=/usr/bin/bigfred

case "$1" in
start)
	[ -x "$BIN" ] || exit 0
	exec "$BIN"
	;;
stop)
	killall bigfred 2>/dev/null
	;;
restart)
	$0 stop
	$0 start
	;;
*)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
	;;
esac
