#!/bin/sh
# Grafana OSS (BR2_PACKAGE_GRAFANA)

GRAFANA_BIN=/usr/bin/grafana-server
GRAFANA_HOME=/usr/share/grafana
GRAFANA_CFG=/etc/grafana/grafana.ini

case "$1" in
start)
	[ -x "$GRAFANA_BIN" ] || exit 0
	[ -f "$GRAFANA_CFG" ] || exit 0
	mkdir -p /data/opt/grafana/data /data/opt/grafana/log /data/opt/grafana/plugins
	exec taskset -c 0,1 "$GRAFANA_BIN" \
		--homepath="$GRAFANA_HOME" \
		--config="$GRAFANA_CFG"
	;;
stop)
	killall grafana-server 2>/dev/null
	;;
restart)
	$0 stop
	$0 start
	;;
*)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
	;;
esac
