package supervisord

import (
	"os"
	"path/filepath"
	"testing"
)

const sampleConfig = `; Generated by BigFred
[group:infra]
programs=redis

[group:loco]
programs=scripts-executor

[program:redis]
command=/bin/bash -c 'valkey-server --port 6379'
autostart=true
autorestart=true

[program:scripts-executor]
command=/bin/bash -c '/usr/bin/loco scripts-executor'
autostart=true
autorestart=false
`

func TestParsePrograms(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "supervisord.conf")
	if err := os.WriteFile(path, []byte(sampleConfig), 0o644); err != nil {
		t.Fatal(err)
	}

	progs, err := ParsePrograms(path)
	if err != nil {
		t.Fatal(err)
	}
	if len(progs) != 2 {
		t.Fatalf("expected 2 programs, got %d", len(progs))
	}

	byName := map[string]programDef{}
	for _, p := range progs {
		byName[p.Name] = p
	}
	if byName["redis"].Group != "infra" {
		t.Fatalf("redis group: %q", byName["redis"].Group)
	}
	if byName["scripts-executor"].Group != "loco" {
		t.Fatalf("executor group: %q", byName["scripts-executor"].Group)
	}
	if !byName["redis"].Autostart {
		t.Fatal("redis autostart expected true")
	}
	if byName["scripts-executor"].Autostart != true {
		t.Fatal("executor autostart expected true")
	}
}

func TestParseProgramsMissingFile(t *testing.T) {
	_, err := ParsePrograms(filepath.Join(t.TempDir(), "missing.conf"))
	if !os.IsNotExist(err) {
		t.Fatalf("expected not exist, got %v", err)
	}
}

func TestValidateName(t *testing.T) {
	cases := []struct {
		name string
		ok   bool
	}{
		{"redis", true},
		{"scripts-executor", true},
		{"dcc-bus-1-2", true},
		{"Bad", false},
		{"", false},
		{"../redis", false},
	}
	for _, tc := range cases {
		err := validateName(tc.name)
		if tc.ok && err != nil {
			t.Fatalf("%q: expected ok, got %v", tc.name, err)
		}
		if !tc.ok && err == nil {
			t.Fatalf("%q: expected error", tc.name)
		}
	}
}

func TestParseStatusOutput(t *testing.T) {
	rows := parseStatusOutput("redis RUNNING pid 42, uptime 0:01:00\nscripts-executor STOPPED\n")
	if len(rows) != 2 {
		t.Fatalf("rows: %d", len(rows))
	}
	if rows[0].Name != "redis" || rows[0].Status != "RUNNING" || rows[0].PID != 42 {
		t.Fatalf("redis: %+v", rows[0])
	}
	if rows[1].Name != "scripts-executor" || rows[1].Status != "STOPPED" {
		t.Fatalf("executor: %+v", rows[1])
	}
}
